### ISSUE TITLE
Fans can see teams current and future financial status without signup

### ISSUE THREAD

**Issue by efetuzun** [SU-CS308-22FA/CS-308-Team-19-202201#12]
As a team supporter, I want to access financial status of the teams and see future predictions of their financial performance anonymously without signing up to the system, therefore I can browse the data without having to bother with unnecessary sing-up and login procedures each time I enter the website.

Definitions of Done: 

- [ ] I can view the home page.
- [ ] I can click on 'Teams' on the app bar.
- [ ] I am then redirected to another page.
- [ ] There, I can then view the graphs about all teams.

**Comment by tanersnmz** [comment]
QA tests were done and all is working according to definitions of done. Good Job! @efetuzun
