### ISSUE TITLE
A soccer player can see the budgets of the teams.

### ISSUE THREAD

**Issue by efetuzun** [SU-CS308-22FA/CS-308-Team-19-202201#13]
As a player, I want to see the expenses and revenues of the team I am going to go transfer so that I can see if the team can actually cover my salary.

Definitions of Done:

- [ ] I can view the home page.
- [ ] I can click on 'Teams' on the app bar.
- [ ] I am then redirected to another page.
- [ ] There, I can then view the graphs about all teams. 
- [ ] I can select an individual team to view detailed information.
- [ ] I am redirected to the individual page of that team.
- [ ] I can see their graphs, with some team based information.

**Comment by tanersnmz** [comment]
QA tests were done and all is working according to definitions of done. Good Job! @efetuzun
