### ISSUE TITLE
TFF Admins can add new teams to the system.

### ISSUE THREAD

**Issue by efetuzun** [SU-CS308-22FA/CS-308-Team-19-202201#24]
As a TFF admin, I want to add new teams at the beginning of the season so that I can keep track of their financial status.
Definitions of Done:

- [ ] After I am logged in, I can see the navigation bar and the profile page with my name.
- [ ] I can click on Add Team button.
- [ ] I am redirected to another page that includes a form.
- [ ] I can enter the team's name and season starting budget determined by TFF.
- [ ] If I enter the budget to be less than or equal to zero, I am prompted with an error.
- [ ] If I try to enter a team that is already in the database, I am prompted with a message.
- [ ] If I enter information correctly, the page alerts me and then I am directed to my profile page
- [ ] On the teams page, I can see the team I added without a graph, as there is no information submitted yet.

**Comment by tanersnmz** [comment]
QA tests were done and all is working according to definitions of done. Good Job! @efetuzun
