### ISSUE TITLE
Team admins can update the information about their team.

### ISSUE THREAD

**Issue by efetuzun** [SU-CS308-22FA/CS-308-Team-19-202201#30]
As a team admin, I want to be able to update my team's information so it can be represented correctly on the FFP.

Definitions of Done:

- [ ] Team admins can login.
- [ ] Team admins can view their team by clicking on 'My Team' on the navigation bar.
- [ ] Team admins can see the form where they can update their teams information.
- [ ] Team admins can send the request to update their team's information.
- [ ] Errors appear if there is any problem with the process.
- [ ] After success, they are redirected to their profile page.
- [ ] If they view the information once again, it is updated.

**Comment by tanersnmz** [comment]
QA tests were done and all is working according to definitions of done. Good Job! @efetuzun
