### ISSUE TITLE
Team admins can view the current status of files submitted.

### ISSUE THREAD

**Issue by efetuzun** [SU-CS308-22FA/CS-308-Team-19-202201#31]
As a team admin, I can see the status of the files I submitted so that I can decide if I need to take legal actions.
Definitions of Done

- [ ] After I am logged in, I can see the 'Status' on the navigation bar.
- [ ] Clicking on 'Status' redirects me to the status page where I can see status of my submitted files
- [ ] I can see the status of each file, with some past ones 'Done' and current ones 'Submitted', 'In Review' or 'Done'.
- [ ] I only see the status of my team's files.
- [ ] If there are no files, the page is empty.

**Comment by tanersnmz** [comment]
QA tests were done and all is working according to definitions of done. Good Job! @efetuzun
