### ISSUE TITLE
TFF Admins can delete teams from the system.

### ISSUE THREAD

**Issue by tanersnmz** [SU-CS308-22FA/CS-308-Team-19-202201#37]
As a TFF admin, I want to delete teams at the beginning of the season so that I can keep track of desired teams' financial status.

Definitions of Done:

- [x] I can view the profile page.

- [x] I can click on "DELETE TEAM" on the app bar.

- [x] I am then redirected to another page.
- [x] There, I can see all teams.
- [x] There, I can click the delete button for the desired team.
- [x] If there is a problem while deleting,  I see an error message.
- [x]  If deletion is successful, then the team is deleted, admin of the team gets a notification with an email and the page will be automatically refreshed.

**Comment by efetuzun** [comment]
This feature is correctly developed. Passed the tests. Well done, Taner!
